### ISSUE TITLE
Declare/update license

### ISSUE THREAD

**Issue by crawfxrd** [system76/firmware-smmstore#9]
- What _is_ the license?
  - It appears to be ICU variant of the MIT license (SPDX: ICU), although the paragraph order is different.
- Which portions, if any, are copyright Eric Holk?
- Can and should we change the license to something else?
  - MIT, or at least match the ICU variant text?

**Comment by ids1024** [comment]
The additional cause seems to also be in https://spdx.org/licenses/X11.html, though likewise in a different order.

**Comment by jackpot51** [comment]
I believe nearly if not all of the code from the original rustboot program has been removed. But without confirmation of that, firmware-setup, firmware-update, and gop-policy all share this license

**Comment by crawfxrd** [comment]
IANAL

AFAICT, the license file comes from [bootloader-efi](https://gitlab.redox-os.org/redox-os/bootloader-efi).

The last commit form Eric Holk was [ee8fb7bbfddaf](https://gitlab.redox-os.org/redox-os/bootloader-efi/-/commits/ee8fb7bbfddaf1b09256d2ed9e4f3fe0ad42da95).

But instead let's look at [93d89ed69ed89](https://gitlab.redox-os.org/redox-os/bootloader-efi/-/commits/93d89ed69ed89060a8969ccce0ceebe9ceef5b17).

This contains all commits prior to any contributions by Jeremy Soller.

```
[~/redox/bootloader-efi]$ gs
HEAD detached at 93d89ed
nothing to commit, working tree clean
[~/redox/bootloader-efi]$ git shortlog -sn
    17  Eric Holk
     1  C. Jeremiah Schneider
     1  Chang Liu
     1  Piotr Czarnecki
```

Comparing the code:

`Makefile`: Completely rewritten
`Cargo.toml`: Completely rewritten
`Cargo.lock`: Machine generated; not applicable

The only shared Rust code I see are enabling features, which by themselves cannot be considered copyrightable.

- `#![no_std]`
- `#![feature(asm)]` (renamed `#![feature(llvm_asm)]`)
- The prelude import, which is dead code in firmware-smmstore

---

bootloader-efi also contains 5 commits by "4lDO2". These commits have no relation to any file that share the same name in, or any functionality implemented by, firmware-smmstore.

---

So it would seem Jeremy Soller, as an individual, and System76 are the only persons who can claim copyright to this code.

**Comment by jackpot51** [comment]
Yep, I agree with that assessment. If it is the same story in the other four firmware apps, I think we can switch the license to GPLv3

**Comment by crawfxrd** [comment]
Does it have to be compatible with GPLv2 due to coreboot?

The face that this uses the SMI interface and does not directly call coreboot code seems sufficient in terms of using/linking GPL code.

But wouldn't the use of firmware-smmstore in the firmware be considered a combined work, not an aggregation of works?

**Comment by jackpot51** [comment]
EFI firmware is not statically linked, each driver or program can be under a different license
